# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.9.0
_src_path: gh:FollowTheProcess/go_copier
author_email: tomfleet2018@gmail.com
author_name: Tom Fleet
create_github_repo: false
description: Blah
github_url: https://github.com/FollowTheProcess/msg
github_username: FollowTheProcess
initialise_git_repo: false
license: MIT License
project_name: msg
project_slug: msg
project_type: library
