project_name: msg

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

archives:
  - id: msg
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}

sboms:
  - id: msg
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version }}

checksum:
  name_template: checksums.txt

changelog:
  # The changelog is handled by release drafter
  skip: true
